[package]
name = "rabin"
version = "0.1.0"
authors = ["Benjamin Heatwole <bheatwole@cwi-va.com>"]
edition = '2018'

[dependencies]
digest = "0.8.0"
sha2 = "0.8.0"
sha3 = "0.8.1"

[dev-dependencies]
rand = "0.6.5"